// Generated by CoffeeScript 1.3.3
(function() {
  var Fconfig;

  Fconfig = (function() {

    Fconfig.prototype.data = {};

    Fconfig.prototype.dir = process.cwd() + '/configs/';

    Fconfig.prototype.files = [];

    function Fconfig(settings) {
      var _ref, _ref1;
      this.env_default = (_ref = settings.env_default) != null ? _ref : 'default';
      this.env = (_ref1 = process.env.NODE_ENV) != null ? _ref1 : this.env_default;
      if (settings.dir) {
        this.dir = settings.dir;
      }
      if (settings.config) {
        this.files.push(this.dir + settings.config);
        this.parseConfigs();
      }
    }

    Fconfig.prototype.parseConfigs = function() {
      var fc, file, k, v, _i, _len, _ref, _results;
      _ref = this.files;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        fc = require(file);
        if (fc[this.env_default]) {
          this.data[this.env_default] = fc[this.env_default];
          delete fc[this.env_default];
        }
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (k in fc) {
            v = fc[k];
            _results1.push(this.data[k] = this._merge(this._merge(v, {}), this._merge(this.data[this.env_default], {})));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Fconfig.prototype.get = function(k, env) {
      env = env != null ? env : this.env;
      if (!k) {
        return this.data[env];
      }
      if (~k.indexOf(".")) {
        return this._getDotNotated(k, env);
      }
      return this.data[env][k];
    };

    Fconfig.prototype._getDotNotated = function(k, env) {
      var walker;
      walker = function(o, i) {
        return o[i];
      };
      return k.split(".").reduce(walker, this.data[env]);
    };

    Fconfig.prototype._merge = function(a, b) {
      var k, v;
      for (k in a) {
        v = a[k];
        b[k] = v;
      }
      return b;
    };

    return Fconfig;

  })();

  module.exports = Fconfig;

}).call(this);
